service: rimac-appointment

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  stage: production
  memorySize: 512
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - sns:Publish
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/*
        - arn:aws:sns:us-east-1:*:AppointmentTopic
  environment:
    NODE_ENV: production
    NODE_PORT: 3000
    AWS_SNS_TOPIC_ARN:
      Ref: AppointmentTopic

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  eventHandler:
    handler: dist/infraestructure/handlers/eventbridge.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSFromEventBridge, Arn]

plugins:
  - serverless-jetpack
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!node_modules/aws-sdk/**'
    - '!test/**'
    - '!**/*.spec.ts'

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
    useChildProcesses: true

resources:
  Resources:
    AppointmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AppointmentTable
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
          - AttributeName: scheduleId
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: insuredId
            AttributeType: S
          - AttributeName: scheduleId
            AttributeType: N

    AppointmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: AppointmentTopic

    SQSFromEventBridge:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs_eventbridge_to_nest

  Outputs:
    AppointmentTopicArn:
      Value:
        Ref: AppointmentTopic
      Export:
        Name: rimac-appointment-topic-arn
